---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  labels:
    app: maintenance
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
      - name: maintenance
        image: schulcloud/maintenance-site:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "1m"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: maintenance
  labels:
    app: maintenance
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: maintenance
